[entryPoints]
[entryPoints.web]
address = ":8085"
reusePort = false

[entryPoints.traefik]
address = ":8086"
reusePort = false

[api]
dashboard = true
insecure = false

[providers.file]
directory = "/config"

[log]
level = "INFO"
filePath = "/var/log/traefik.log"
format = "json"

[accessLog]
filePath = "/var/log/traefik-access.log"
format = "common"

[accessLog.fields]
defaultMode = "keep"

[accessLog.fields.headers]
defaultMode = "keep"

[accessLog.filters]
statusCodes = ["200-599"]
retryAttempts = true
minDuration = "10ms"

[tracing]
addInternals = true

[metrics]
[metrics.prometheus]
addEntryPointsLabels = true
addServicesLabels = true
